### ISSUE TITLE
Update timezone data

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/calendar-js#287]
https://github.com/nextcloud/calendar-js/tree/main/resources/timezones is outdated.

Ref https://github.com/nextcloud/calendar-js/issues/273#issuecomment-888064627. https://github.com/libical/vzic/ might be a good source for the latest data.

**Comment by ChristophWurst** [comment]
https://help.nextcloud.com/t/wrong-time-in-mexico-we-dropped-dst-last-year/159842 Mexico no longer has DST.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/calendar/pull/397 is where the script was added to our repos. It looks rather copied than created by Georg. Hence I wonder if there is a newer version if our copy no longer works.

**Comment by ChristophWurst** [comment]
https://github.com/add2cal/timezones-ical-library looks maintained too

**Comment by tcitworld** [comment]
Mozilla stopped using the python updater script a few months ago, so we probably shouldn't rely on it too much in the future: https://hg.mozilla.org/comm-central/rev/2b430305eaf46970d62e9569e1800d5c4be9071c
