### ISSUE TITLE
Extract timezone stuff into it's own library

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/calendar-js#380]
The TimezoneManager is being used in `@nextcloud/vue` for the TimezonePicker. In order to avoid `@nextcloud/vue` to import all of `@nextcloud/calendar-js`, we should try to extract the required stuff from this library into another one.

Should be doable once #304 is closed.

**Comment by ChristophWurst** [comment]
> Should be doable once #304 is closed.

The future is now

**Comment by st3iny** [comment]
The future is here now: https://github.com/nextcloud-libraries/timezones
